// product
export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const EDIT_SINGLE_PRODUCT = "EDIT_SINGLE_PRODUCT";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
// customer
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const EDIT_SINGLE_CUSTOMER = "EDIT_SINGLE_CUSTOMER";
export const ADD_NEW_CUSTOMER = "ADD_NEW_CUSTOMER";
export const GET_SINGLE_CUSTOMER = "GET_SINGLE_CUSTOMER";
// order
export const GET_ORDER = "GET_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const GET_SINGLE_ORDER = "GET_SINGLE_ORDER";
export const EDIT_SINGLE_ORDER = "EDIT_SINGLE_ORDER";

// category
export const GET_CATEGORY = "GET_CATEGORY";

// login
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
